---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role enterprise_catalog
#
# Overview: This role's tasks come from edx_django_service.
#
#
# Dependencies:
#
#
# Example play:
#
#

- name: Add management command user to docker group
  command: "usermod -aG docker enterprise_catalog_mgmt_commands"
  when: edx_django_service_enable_experimental_docker_shim
